### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Tomingz** [foolwood/DaSiamRPN#44]
I run python test_otb.py by py3 in Windows，pytorch0.4.Is the sequence problem？

**Comment by xujiao3628** [comment]
可能是你下载的OTB2015数据集的问题，有的groundtruth_rect.txt文件是空格分开的，有的是逗号，或者你在程序中改一下，或者改一下txt文件

**Comment by xujiao3628** [comment]
我也遇到了这个问题，请问你现在解决了吗？

**Comment by xujiao3628** [comment]
我用的作者用的环境torch0.3.1 py2.7

**Comment by xujiao3628** [comment]
你好，请问用sh直接下载下来的数据集中的东西和OTB2015.json中的内容对应吗？？运行test_otb.py时一直出错

**Comment by Tomingz** [comment]
@xujiao3628，我是之前自己已经下载过OTB2015，就没有用sh下载，然后为了防止和json内不一样，还特地核对了一遍，没有差异，但是依然报错，你的也有这个问题吗？

**Comment by HelloRicky123** [comment]
你们看一下文件权限吧，或者具体读哪个图片读时候读取不到。

**Comment by Tomingz** [comment]
@HelloRicky123 重新下载了数据集，已经解决了，感谢

**Comment by fzh0917** [comment]
我感觉每次跑一个别人的代码，就要手动去下载一个完整的数据集，硬盘有点撑不住了呀。又没找到哪儿是手动改数据集路径的地方。T_T

**Comment by fzh0917** [comment]
> 我感觉每次跑一个别人的代码，就要手动去下载一个完整的数据集，硬盘有点撑不住了呀。又没找到哪儿是手动改数据集路径的地方。T_T

有趣的是，我使用`.sh`文件重新下载了OTB2015数据集，跑`test_otb.py`代码时，还是爆出这个错误。

**Comment by Shiyong2019** [comment]
the same problem,when run demo.py.

....../code$ python demo.py

Traceback (most recent call last):
  File "demo.py", line 36, in <module>
    state = SiamRPN_track(state, im)  # track
  File "/vol/research/VS-Work/some_code/tmp-test/DaSiamRPN-master/code/run_SiamRPN.py", line 177, in SiamRPN_track
    x_crop = Variable(get_subwindow_tracking(im, target_pos, p.instance_size, round(s_x), avg_chans).unsqueeze(0))
  File "/vol/research/VS-Work/some_code/tmp-test/DaSiamRPN-master/code/utils.py", line 56, in get_subwindow_tracking
    im_sz = im.shape 
AttributeError: 'NoneType' object has no attribute 'shape'

enviroment info:
utubun 16.04 ,
......../code$ conda list
# Name                    Version                   Build  Channel
numpy                     1.15.4           py27h1d66e8a_0 
opencv                    2.4.11                 nppy27_0    menpo

**Comment by foolwood** [comment]
@Shiyong2019 
Maybe you meet a problem with reading pictures.
check this part.
```
image_files = sorted(glob.glob('./bag/*.jpg'))
print(image_files)
```

**Comment by fzh0917** [comment]
@Shiyong2019 
I ran `demo.py` well, but got the same error when running `test_otb.py`.

**Comment by Shiyong2019** [comment]
thank you!@foolwood
I checked, 
But why sometimes can not read pictures successfully? 
for example,No.9~13 pictures can not be readed?
.....
./bag/00000006.jpg
SiamRPN_track
./bag/00000007.jpg
SiamRPN_track
./bag/00000008.jpg
SiamRPN_track
./bag/00000014.jpg
SiamRPN_track
./bag/00000015.jpg
SiamRPN_track
./bag/00000016.jpg
SiamRPN_track
./bag/00000017.jpg
SiamRPN_track
./bag/00000018.jpg
SiamRPN_track
./bag/00000019.jpg
SiamRPN_track
./bag/00000020.jpg
SiamRPN_track
./bag/00000025.jpg
SiamRPN_track
